name: CI - Test

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

# Define the events that trigger this workflow
on:
  pull_request:
    branches: ['develop']
    paths-ignore: ['docs/**']
  push:
    branches: ['develop']
    paths-ignore: ['docs/**']

# Define concurrency settings to ensure multiple workflows don't interfere
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
      - name: Build Local Environment
        run: |
          docker compose -f ./compose/local/docker-compose.yml build django
      - name: Run DB Migrations in Local Environment
        run: |
          docker compose -f ./compose/local/docker-compose.yml run --rm django python manage.py migrate
      - name: Run Tests in Local Environment
        run: |
          docker compose -f ./compose/local/docker-compose.yml run django pytest
      - name: Tear down Local Environment
        run: |
          docker compose -f ./compose/local/docker-compose.yml down
      - name: Create Pull Request from Develop to Main
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITPR_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh pr create --base main --head develop --title "Merge Develop to Main" --body "Automated PR created after successful tests."
